DROP TABLESPACE IPA_TS INCLUDING CONTENTS 
        CASCADE CONSTRAINTS

CREATE TABLESPACE IPA_TS DATAFILE 'C:\Oracle\TS_IPA.dat'
SIZE 7M REUSE AUTOEXTEND ON NEXT 5M MAXSIZE 30M

ALTER USER C##IPA QUOTA 2M ON IPA_TS;

COMMIT

--DROP TABLESPACE IPA_TS_TEMP

CREATE TEMPORARY TABLESPACE IPA_TS_TEMP TEMPFILE 'C:\Oracle\TS_IPA_TEMP.dbf'
SIZE 5M REUSE AUTOEXTEND ON NEXT 3M MAXSIZE 20M

COMMIT

SELECT * FROM Sys.DBA_TABLESPACES
SELECT * FROM Sys.DBA_TABLESPACES
Where tablespace_name = 'IPA_TS'
SELECT tablespace_name, file_name FROM dba_data_files 
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE ROLE RLIPACORE;

COMMIT

GRANT CREATE SESSION TO RLIPACORE;

GRANT CONNECT,CREATE SESSION, CREATE ANY TABLE,
DROP ANY TABLE, CREATE ANY VIEW,
DROP ANY VIEW, CREATE ANY PROCEDURE,
DROP ANY PROCEDURE TO RLIPACORE
---DROP ROLE RLIPACORE
SELECT * FROM dba_roles WHERE ROLE = 'RLIPACORE';

COMMIT

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RLIPACORE';

CREATE PROFILE PF_IPACORE LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30

SELECT * FROM DBA_PROFILES;

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_IPACORE';

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';
 --новы ipacore
--DROP USER IPACORE
CREATE USER IPACORE IDENTIFIED BY rlipacore
DEFAULT TABLESPACE IPA_TS
TEMPORARY TABLESPACE IPA_TS_TEMP
PROFILE PF_IPACORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT CREATE SESSION TO IPACORE

GRANT CREATE SESSION TO C##IPA

ALTER USER IPACORE QUOTA 2M ON IPA_TS;

ALTER TABLESPACE IPA_TS OFFLINE;

DROP USER C##TESTLOL

CREATE USER C##TESTLOL IDENTIFIED BY RLIPACORE
    DEFAULT TABLESPACE IPA_TS
    TEMPORARY TABLESPACE IPA_TS_TEMP
    PROFILE PF_IPACORE
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;
    
GRANT RLIPACORE TO C##TESTLOL

COMMIT

ALTER TABLESPACE IPA_TS ONLINE;

SELECT *
FROM dba_users
ORDER BY username;
