SET SERVEROUTPUT ON;

DROP TABLE T_RANGE;
CREATE TABLE T_RANGE
(
    X NUMERIC(4, 0)
)
PARTITION BY RANGE (X)
(
    PARTITION LESS_THAN_HUNDRED VALUES LESS THAN (100),
    PARTITION RANGE_DEFAULT VALUES LESS THAN (MAXVALUE)
);

DROP TABLE T_INTERVAL;

CREATE TABLE T_INTERVAL
(
    Birthday DATE
)
PARTITION BY RANGE (Birthday)
INTERVAL (NUMTOYMINTERVAL(1, 'YEAR'))
(
    PARTITION Before_Covid VALUES LESS THAN (TO_DATE('2020-01-01', 'YYYY-MM-DD'))
);

CREATE TABLE T_HASH
(
    LOL VARCHAR2(100)
)
PARTITION BY HASH (LOL)
PARTITIONS 5;

CREATE TABLE T_LIST
(
    X CHAR(1)
)
PARTITION BY LIST (X)
(
    PARTITION A_A VALUES ('A'),
    PARTITION B_B VALUES ('B'),
    PARTITION C_C VALUES ('C'),
    PARTITION DEF_AULT VALUES (DEFAULT)
);

SELECT * FROM USER_TAB_PARTITIONS;

INSERT INTO T_RANGE (X) VALUES (60); 
INSERT INTO T_RANGE (X) VALUES (40); 
INSERT INTO T_RANGE (X) VALUES (150);
COMMIT;

SELECT * FROM T_RANGE PARTITION(LESS_THAN_HUNDRED);
SELECT * FROM T_RANGE PARTITION(RANGE_DEFAULT);

INSERT INTO T_INTERVAL (Birthday) VALUES (DATE '2019-01-01'); 
INSERT INTO T_INTERVAL (Birthday) VALUES (DATE '2021-01-01');
COMMIT;
SELECT * FROM USER_TAB_PARTITIONS;

SELECT * FROM T_INTERVAL PARTITION(BEFORE_COVID);
SELECT * FROM T_INTERVAL PARTITION(SYS_P361);

INSERT INTO T_HASH (LOL) VALUES ('Alpha');
INSERT INTO T_HASH (LOL) VALUES ('Bravo');
INSERT INTO T_HASH (LOL) VALUES ('Charlie');
INSERT INTO T_HASH (LOL) VALUES ('Delta');
INSERT INTO T_HASH (LOL) VALUES ('Echo');
COMMIT;

SELECT * FROM T_HASH PARTITION(SYS_P341);
SELECT * FROM T_HASH PARTITION(SYS_P342);
SELECT * FROM T_HASH PARTITION(SYS_P343);
SELECT * FROM T_HASH PARTITION(SYS_P344);
SELECT * FROM T_HASH PARTITION(SYS_P345);

INSERT INTO T_LIST (X) VALUES ('A');
INSERT INTO T_LIST (X) VALUES ('B'); 
INSERT INTO T_LIST (X) VALUES ('C'); 
INSERT INTO T_LIST (X) VALUES ('D'); 
COMMIT;

SELECT * FROM T_LIST PARTITION(A_A);
SELECT * FROM T_LIST PARTITION(B_B);
SELECT * FROM T_LIST PARTITION(C_C);
SELECT * FROM T_LIST PARTITION(DEF_AULT);

SELECT * FROM T_RANGE PARTITION(LESS_THAN_HUNDRED);
UPDATE T_RANGE SET X = 150 WHERE X = 50;
COMMIT;
SELECT * FROM T_RANGE PARTITION(RANGE_DEFAULT);

SELECT * FROM T_INTERVAL PARTITION(BEFORE_COVID);
UPDATE T_INTERVAL SET Birthday = DATE '2021-01-01' WHERE Birthday = DATE '2019-01-01';
COMMIT;
SELECT * FROM T_INTERVAL PARTITION(SYS_P361);

SELECT * FROM T_HASH PARTITION(SYS_P341);
SELECT * FROM T_HASH PARTITION(SYS_P342);
SELECT * FROM T_HASH PARTITION(SYS_P343);
SELECT * FROM T_HASH PARTITION(SYS_P344);
SELECT * FROM T_HASH PARTITION(SYS_P345);
UPDATE T_HASH SET LOL = 'NewAlpha' WHERE LOL = 'Alpha';
COMMIT;
SELECT * FROM T_HASH PARTITION(SYS_P341);
SELECT * FROM T_HASH PARTITION(SYS_P342);
SELECT * FROM T_HASH PARTITION(SYS_P343);
SELECT * FROM T_HASH PARTITION(SYS_P344);
SELECT * FROM T_HASH PARTITION(SYS_P345);

SELECT * FROM T_LIST PARTITION(A_A);
UPDATE T_LIST SET X = 'D' WHERE X = 'A';
COMMIT;
SELECT * FROM T_LIST PARTITION(DEF_AULT);

ALTER TABLE T_RANGE
ADD PARTITION LESS_THAN_THREE_HUNDRED VALUES LESS THAN (3000);
INSERT INTO T_RANGE (X) VALUES (2500);
COMMIT;
ALTER TABLE T_RANGE
MERGE PARTITIONS RANGE_DEFAULT, LESS_THAN_THREE_HUNDRED INTO PARTITION LESS_THAN_THREE_K;
SELECT * FROM T_RANGE PARTITION(LESS_THAN_THREE_K);

ALTER TABLE T_RANGE
SPLIT PARTITION LESS_THAN_HUNDRED AT (50) INTO
(
    PARTITION LESS_THAN_FT,
    PARTITION AAAAAAAAAAAAAAAAAAAAAA
);

SELECT * FROM T_RANGE PARTITION(LESS_THAN_FT);
SELECT * FROM T_RANGE PARTITION(AAAAAAAAAAAAAAAAAAAAAA);

CREATE TABLE TEMP_LESS_THAN_HUNDRED
(
    X NUMERIC(4,0)
);

CREATE TABLE TEMP_LESS_THAN_TWO_HUNDRED
(
    X NUMERIC(4,0)
);
ALTER TABLE T_RANGE
EXCHANGE PARTITION LESS_THAN_FT WITH TABLE TEMP_LESS_THAN_HUNDRED WITHOUT VALIDATION;

ALTER TABLE T_RANGE
EXCHANGE PARTITION AAAAAAAAAAAAAAAAAAAAAA WITH TABLE TEMP_LESS_THAN_TWO_HUNDRED WITHOUT VALIDATION;

ALTER TABLE T_RANGE
EXCHANGE PARTITION LESS_THAN_FT WITH TABLE TEMP_LESS_THAN_TWO_HUNDRED WITHOUT VALIDATION;

ALTER TABLE T_RANGE
EXCHANGE PARTITION AAAAAAAAAAAAAAAAAAAAAA WITH TABLE TEMP_LESS_THAN_HUNDRED WITHOUT VALIDATION;

SELECT * FROM T_RANGE PARTITION(LESS_THAN_FT);
SELECT * FROM T_RANGE PARTITION(AAAAAAAAAAAAAAAAAAAAAA);

SELECT TABLE_NAME
FROM USER_PART_TABLES;

SELECT PARTITION_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_RANGE';

SELECT *
FROM T_RANGE PARTITION (LESS_THAN_HUNDRED);

DECLARE
  partition_name VARCHAR2(30);
  sql_query VARCHAR2(1000);
  x_value T_RANGE.X%TYPE;
  c SYS_REFCURSOR;
BEGIN
  SELECT PARTITION_NAME INTO partition_name
  FROM USER_TAB_PARTITIONS
  WHERE TABLE_NAME = 'T_RANGE' AND PARTITION_NAME = 'LESS_THAN_HUNDRED';
  sql_query := 'SELECT X FROM T_RANGE PARTITION (' || partition_name || ')';
  OPEN c FOR sql_query;
  LOOP
    FETCH c INTO x_value;
    EXIT WHEN c%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('Value of X: ' || x_value);
  END LOOP;
  CLOSE c;
END;