CREATE TABLESPACE PDB_TS DATAFILE 'C:\Oracle\PDB.dat'
SIZE 7M REUSE AUTOEXTEND ON NEXT 5M MAXSIZE 30M

CREATE ROLE PDB_ROLE;

COMMIT

GRANT CREATE SESSION TO PDB_ROLE;

GRANT CONNECT,CREATE SESSION, CREATE ANY TABLE,
DROP ANY TABLE, CREATE ANY VIEW,
DROP ANY VIEW, CREATE ANY PROCEDURE,
DROP ANY PROCEDURE TO PDB_ROLE;

CREATE PROFILE PF_PDB LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30

CREATE USER C##U1_IPA_PDB IDENTIFIED BY U1_IPA_PDB
    DEFAULT TABLESPACE PDB_TS
    PROFILE PF_PDB
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;
    
